services:
  db:
    image: postgres:16
    container_name: gopg-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gopg-postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gopg-postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    container_name: app-api
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: gopg-postgres
      DB_SSLMODE: disable
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata: